// Standard library headers before GKC headers (pragma pack hygiene).
#include <string>
#include <utility>

#include <dlfcn.h>

#include "src/apphost/plugin_loader.h"

#include "base/GkcDef.h"

PluginLoader::PluginLoader() = default;

PluginLoader::~PluginLoader() {
    // Release the dynamic library mapping owned by this loader.  If plugin
    // code is still executing when this runs, the caller has a lifetime bug;
    // AppHost calls plugin_.run() to completion before destruction.
    if (handle_ != nullptr) {
        dlclose(handle_);
        handle_ = nullptr;
        entry_  = nullptr;
    }
}

bool PluginLoader::open(const std::string& plugin_path) {
    last_error_.clear();

    // dlopen maps the compiled plugin .so into the current AppHost process.
    // After this succeeds, the plugin's code, static data, and exported
    // symbols are present in this process, but no plugin business logic has
    // run yet.  We still need dlsym() to find the agreed startup function.
    //
    // RTLD_LOCAL keeps the plugin's symbols (especially its own copy of
    // GKC::g_ui_host) private to the plugin .so, so multiple plugins or
    // a future re-load do not collide.
    void* h = dlopen(plugin_path.c_str(), RTLD_NOW | RTLD_LOCAL);
    if (h == nullptr) {
        const char* err = dlerror();
        last_error_ = err != nullptr ? err : "dlopen failed";
        return false;
    }

    // Clear any pending dlerror state before dlsym so we can detect a
    // legitimate "symbol exists but is null" vs "symbol missing" — the
    // recommended POSIX dlsym error-check pattern.
    dlerror();

    // _SA_UIMain is the one symbol AppHost requires every GKC SA plugin to
    // export.  It is generated by the plugin-side GkcGui.cpp shim and has C
    // linkage, so the symbol name is stable and not C++-mangled.
    //
    // If this lookup fails, AppHost cannot enter the plugin at all: it does
    // not know the plugin's C++ ProgramEntryPoint or window class names.
    void* sym = dlsym(h, "_SA_UIMain");
    const char* dlerr = dlerror();
    if (dlerr != nullptr) {
        last_error_ = dlerr;
        dlclose(h);
        return false;
    }

    handle_ = h;

    // dlsym returns a raw address inside the mapped .so.  Casting it to
    // EntryFn makes AppHost able to call it like a normal function:
    //
    //   entry_(lcHost, args)
    //
    // The signature must match the GKC shim exactly:
    //   int _SA_UIMain(const LcInterface<IUiHost>&,
    //                  const ConstArray<ConstStringS>&)
    entry_  = reinterpret_cast<EntryFn>(sym);
    return true;
}

int PluginLoader::run(const GKC::LcInterface<GKC::IUiHost>& lcHost) {
    if (entry_ == nullptr) return -1;

    // M4: pass an empty args array.  ConstArray<ConstStringS> default
    // ctor yields {nullptr, 0} which the plugin's GuiMain treats as
    // "no command-line arguments".
    GKC::ConstArray<GKC::ConstStringS> args;

    // This call crosses from AppHost code into plugin code.  Inside the plugin
    // shim, _SA_UIMain stores lcHost into the plugin-local GKC::g_ui_host and
    // then calls ProgramEntryPoint::GuiMain(args).  Once GuiMain starts,
    // plugin-side GKC wrappers can call back into AppHost's UiHostImpl through
    // that injected lcHost function table.
    return entry_(lcHost, args);
}
