cc_test(
    name = "io_pool_test",
    srcs = ["io_pool_test.cpp"],
    deps = [
        "//third_party:GkcSys",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
    copts = ["-std=c++17"],
)
